config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "phone_numbers#index"
  resources :phone_numbers do
  	collection do
  		get :genrate_numbers
  		post :assign_a_requested_number
  		get :assign_a_number
  	end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/phone_number.rb
class PhoneNumber < ApplicationRecord

	scope :available_numbers, -> { where(assigned: false) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController
	def genrate_numbers
		(1111..1141).each do |number|
			PhoneNumber.create(no: number, assigned: false)
		end
		redirect_to phone_numbers_path
	end

	def assign_a_requested_number
		requested_number = PhoneNumber.available_numbers.find_by(no: params["no"].to_i)
		if requested_number.present?
			requested_number.update_attributes(assigned: true)
			redirect_to phone_number_path(requested_number)
		else
			redirect_to phone_numbers_path, flash[:error] = "Not Available"
		end 
	end

	def assign_a_number
		offset = rand(PhoneNumber.available_numbers.count)
		phone_number_to_assign = PhoneNumber.available_numbers.offset(offset).first
		if phone_number_to_assign.present?
			phone_number_to_assign.update_attributes(assigned: true)
			redirect_to phone_number_path(phone_number_to_assign)
		else
			redirect_to phone_numbers_path, flash[:error] = "Not Available"
		end 
	end

	def show
		@phone_number = PhoneNumber.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phone_numbers_helper.rb
module PhoneNumbersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AssignPhoneNumber</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/phone_numbers/index.html.erb
<h2>Available No</h2>


<%=link_to "Genrate PhoneNumbers", genrate_numbers_phone_numbers_path%>
<%=link_to "Assign a Number", assign_a_number_phone_numbers_path%>

<%= form_with url: assign_a_requested_number_phone_numbers_path do |form| %>
  <%= form.text_field :no %>
  <%= form.submit "Assign Requested_number"%>
<% end %>

app/views/phone_numbers/show.html.erb
<p>Phone Number <h3><%=@phone_number.no%></h3> assigned to you.

<br/>
	<%=link_to "Back to Home Page", phone_numbers_path%>